[tool.poetry]
name = "ollama-commit-message"
version = "0.1.0"
description = ""
authors = ["chenyyu <chenyyu@paypal.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
